### PR TITLE
Feature/update reset password method

### PR DESCRIPTION
**Pull request by emily40830**
modify the request body due to endpoint `auth/reset-password ` updated

Related pull request :
[loadestar-app-backend/Feature/update reset password method](https://github.com/lodestar-cc/lodestar-app-backend/pull/29)

### CODE REVIEW

**Comment by emily40830** [comment]
[(8) 【資安】修正後端資安問題[4]](https://trello.com/c/3c7QC2RX/2202-8-%E3%80%90%E8%B3%87%E5%AE%89%E3%80%91%E4%BF%AE%E6%AD%A3%E5%BE%8C%E7%AB%AF%E8%B3%87%E5%AE%89%E5%95%8F%E9%A1%8C)

**Review by kkshyu — APPROVED** [review]

**Comment by kkshyu** [comment]
plz solve the conflict~~

**Review by kkshyu — APPROVED** [review]

**Comment by kkshyu** [comment]
waiting for backend to merge

**Comment by emily40830** [comment]
please review [lodestar-app-admin](https://github.com/urfit-tech/lodestar-app-admin/pull/51) 
having the same modification

**Pull request merged**
