### PR TITLE
feat: modify login to register page by customer

### PR DESCRIPTION
**Pull request by YohaLin**
1. add 'entry_page.first_method' in setting and app_setting.
2. if customer's 'entry_page.first_method' is 'register', show register page after customer click 'cartSubmit' button.

### CODE REVIEW

**Comment by YohaLin** [comment]
[【登入頁】全站登入頁改註冊頁](https://trello.com/c/wnwhCYwZ/2172-%E3%80%90%E7%99%BB%E5%85%A5%E9%A0%81%E3%80%91%E5%85%A8%E7%AB%99%E7%99%BB%E5%85%A5%E9%A0%81%E6%94%B9%E8%A8%BB%E5%86%8A%E9%A0%81)

**Review by Ponchimeow — COMMENTED** [review]
So, there will be two or more methods?
or methods with different priority?

How about change the value to an array 🤔

**Comment by YohaLin** [comment]
@Ponchimeow 
I just make an alternative for skillcollect, and now only skillcollect uses 'entry_page.first_method '.
Do you think there will be 'entry_page.second_method' or something?

**Comment by Ponchimeow** [comment]
As discussed in the afternoon communication, the variable can be changed to `entry_page.method`

**Review by Ponchimeow — APPROVED** [review]

**Comment by kkshyu** [comment]
`auth.entry_method` is easier to be understood

**Pull request merged**
